{
  parserClass="dev.bakakawaii.parser.PygmalionParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Pygmalion"
  psiImplClassSuffix="Impl"
  psiPackage="dev.bakakawaii.psi"
  psiImplPackage="dev.bakakawaii.psi.impl"

  elementTypeHolderClass="dev.bakakawaii.psi.PygmalionTypes"
  elementTypeClass="dev.bakakawaii.psi.PygmalionElementType"
  tokenTypeClass="dev.bakakawaii.psi.PygmalionTokenType"
}

simpleFile ::= item_*

private item_ ::= (statement | CRLF )

statement ::= command (argument | string? )+ flag* CRLF?

flag ::= (flagname argument?) | flagname